owu-uy-community/website

src/components/la-meetup/Hero.astro
"Me interesa asistir" es genero neutral 😄
=> s/Estoy interesado/Me interesa asistir

src/components/home/QueEsOWU.astro, src/pages/index.astro
=> Feature: Que es OWU

src/components/la-meetup/OpenSpace.astro, src/pages/la-meetup/index.astro
=> Add open-space section

src/components/la-meetup/Agenda.astro, src/components/la-meetup/ComingSoon.astro, src/components/la-meetup/Event.astro, src/components/la-meetup/OpenSpace.astro, src/components/la-meetup/Speakers.astro, src/data/la-meetup.json, src/pages/la-meetup/index.astro
=> Update Agenda component to adjust the actual agenda that we have

src/data/la-meetup.json
Corrijo el horario del Coffee break
=> Update coffee break time

src/components/la-meetup/Gallery.astro, src/content/photos.json, src/data/la-meetup.json, src/pages/la-meetup/index.astro
=> Add Gallery section to landing page

src/content/general-config.json, src/data/la-meetup.json
En la nueva version que Agustin esta creando, esta todo unificado en un solo lugar :)
=> fixs: Cambio el enlace de owu por uno que no caduca nunca

package-lock.json, package.json, src/app/layout.tsx
- I've added Vercel Analytics and Speed Insights
- I've added Google Analytics
---
---
---
---
---
=> feat: Add Analytics and Speed Insights ⚡️

src/components/shared/Navbar/index.tsx, src/components/shared/Navbar/mobileNav.tsx, src/components/shared/Sheet/index.tsx
- I've fixed the Navbar links issue
---
---
---
---
---
=> fix: Navbar links

src/components/shared/Navbar/index.tsx, src/components/shared/Navbar/mobileNav.tsx
use usePathname hook and default Link component behavior in order to fix navigation.
#47 
Source: https://github.com/vercel/next.js/discussions/49465
=> Fix navigation

src/components/Landing/CountdownTimer/index.tsx, src/components/Meetups/2024/Hero/index.tsx
Add countdown component in order to display how many days/hours/minutes/ are left for request tickets
#61
=> feat: add countdown component

src/app/(web)/(content)/(meetups)/(2024)/la-meetup/page.tsx, src/app/(web)/(content)/(meetups)/(2024)/la-meetup/services/getMeetup.ts, src/components/Meetups/2024/Communities/index.tsx
- I've added communities
---
---
---
---
---
=> feat: Add communities

src/components/Meetups/2024/Ticket/index.tsx
=> fix: Alignament

src/components/Meetups/2024/Ticket/index.tsx
=> fix: Alignment

src/components/Meetups/2024/Ticket/index.tsx
=> fix: Ticket Sponsors height and margin

src/components/Meetups/2024/Hero/index.tsx
=> fix: Hide ticket before Sep 23, 2024

src/components/Meetups/2024/Hero/index.tsx
=> fix: Add ticket

src/components/Landing/CountdownTimer/index.tsx
=> feat: Improve Countdown

src/app/admin/screen/page.tsx, src/app/lib/videos/remotion/compositions/templates/map/Map.tsx, src/app/lib/videos/remotion/compositions/templates/map/MapContainer.tsx, src/app/lib/videos/remotion/compositions/templates/openspace/OpenSpace.tsx, src/app/lib/videos/remotion/compositions/templates/speakers/SpeakersCard.tsx, src/app/lib/videos/remotion/compositions/templates/speakers/index.tsx, src/app/lib/videos/remotion/compositions/templates/sponsors/index.tsx, src/components/Meetups/2024/Introduction/index.tsx, src/components/Meetups/2024/OpenSpace/Map/index.tsx
=> Add openspace map scenes

src/app/lib/videos/remotion/compositions/templates/map/MapContainer.tsx
=> Fix: Agenda final

src/components/Meetups/2024/OpenSpaceAgenda/index.tsx
=> Fix: Agenda

src/components/Meetups/2024/OpenSpaceAgenda/index.tsx
=> Fix: Agenda 3

src/app/(web)/(content)/(landing)/page.tsx, src/app/(web)/(content)/(meetups)/(2024)/la-meetup/services/getEvents.ts, src/components/Landing/Event/index.tsx, src/components/Landing/Events/index.tsx
=> feat: Show events

src/app/(web)/(content)/(meetups)/(2024)/la-meetup/services/getEvents.ts, src/components/Landing/Event/index.tsx, src/components/Landing/Events/index.tsx
This pull request addresses a critical bug where stale events were being displayed on the landing page due to Next.js caching behavior. Additionally, minor style adjustments have been made to improve responsiveness, with further enhancements planned for a future PR.
- **Issue**: Events displayed on the landing page were not updating as expected because Next.js cached the static content indefinitely.
- **Solution**: Implemented a revalidation strategy to refresh static content every hour (`revalidate: 3600`). 
- This ensures that events are updated regularly while minimizing server load (maximum of 24 regeneration requests per day).
- Made minor adjustments to improve the responsiveness of the event components.
- These changes are foundational and will be expanded upon in subsequent …
=> Improve Events experience :) 🐛

src/app/lib/utils.ts, src/app/lib/videos/remotion/compositions/templates/sponsors/index.tsx, src/components/Meetups/2023/Communities/index.tsx, src/components/Meetups/2023/Speakers/index.tsx, src/components/Meetups/2023/Sponsors/index.tsx, src/components/Meetups/2023/Staff/index.tsx, src/components/Meetups/2024/Speakers/index.tsx, src/components/Meetups/2024/Sponsors/index.tsx, src/components/Meetups/2024/Staff/index.tsx, src/components/Meetups/2025/Sponsors/index.tsx
Replace random array sorting with alphabetical sorting across all meetup sections (Communities, Speakers, Sponsors, Staff) for better consistency and user experience.
- **Added `alphabeticalSort` function** in `src/app/lib/utils.ts`
- Generic function that sorts arrays alphabetically by a specified key
- Defaults to sorting by `name` property
- Supports custom key specification (e.g., `lastname`)
- Handles edge cases with empty arrays and null values
- `Communities/index.tsx` - Now sorts communities alphabetically by name
- `Speakers/index.tsx` - Now sorts speakers alphabetically by name  
- `Sponsors/index.tsx` - Now sorts sponsors alphabetically by name
- `Staff/index.tsx` - Now sorts staff alphabetically by name
- `Speakers/index.tsx` - Now sorts speakers alphabetically by lastname
- …
=> feat: Introduce alphabetical sorting for sponsors, speakers, and staff across Meetup components

src/app/lib/utils.ts, src/components/Landing/Event/index.tsx, src/components/Landing/Hero/index.tsx, src/components/Meetups/2023/Hero/index.tsx, src/components/Meetups/2024/Communities/index.tsx, src/components/Meetups/2024/Gallery/index.tsx, src/components/Meetups/2024/Hero/index.tsx, src/components/Meetups/2024/Member/index.tsx, src/components/Meetups/2025/CallForProposals/index.tsx, src/components/Meetups/2025/Hero/index.tsx, src/components/shared/Footer/index.tsx, src/components/shared/Navbar/index.tsx, src/components/shared/Sponsor/index.tsx
This PR implements UTM parameter tracking for external links throughout the OWU website to measure traffic attribution from La Meetup to external partners, sponsors, and social media platforms.
- **New Utility Function**: Added `addUtmParams()` to `src/app/lib/utils.ts`
- Automatically detects external vs internal links
- Only adds UTM parameters to external URLs (starting with `http/https`)
- Preserves internal navigation without UTM pollution
- Default parameters: `utm_source=la-meetup&utm_medium=owu`
- **utm_source**: `la-meetup` (identifies traffic source)
- **utm_medium**: `owu` (identifies the organization)
- **Social Media**: Instagram, LinkedIn, Slack links in navbar and footer
- **Google Maps**: Location links across all meetup components  
- **Sponsor Websites**: All sponsor …
=> feat: Add UTM Parameters to External Links for Traffic Attribution

content/la-meetup-2025/la-meetup/index.yaml, src/app/(web)/(content)/(meetups)/(2025)/la-meetup/page.tsx, src/app/(web)/(content)/layout.tsx, src/app/(web)/layout.tsx, src/app/globals.css, src/app/layout.tsx, src/app/lib/keystatic/utils.ts, src/components/Meetups/2024/Agenda/index.tsx, src/components/Meetups/2025/Agenda/index.tsx, src/keystatic/collections/la-meetup-2025.ts
This PR implements a complete agenda system for LA Meetup III, transforming the basic event structure into a fully detailed conference schedule with comprehensive event information.
- **Event Details**: Updated with proper title, subtitle, date (Nov 1, 2025), and venue (Sinergia Faro)
- **Call-to-Action Buttons**: Added calendar integration and event details buttons
- **Location Integration**: Google Maps integration for easy venue access
1. **Reception & Breakfast** (9:00-10:00) - Welcome with breakfast and networking
2. **Open Space** (10:00-13:30) - Collaborative idea marketplace
3. **Lunch Break** (13:30-15:00) - Networking break (BYOL or food court)
4. **Talk Slot 1** (15:00-15:40) - TBD from call for proposals
5. **Talk Slot 2** (15:40-16:20) - TBD from call for proposals  
6. …
=> feat: Add La Meetup III Agenda 🗓️

content/la-meetup-2025/la-meetup/index.yaml
Removed "MBC" from La Meetup III agenda until the location is confirmed
=> chore: removed MBC from La Meetup III agenda
